tide configure --auto \
    --style=Rainbow \
    --prompt_colors='True color' \
    --show_time=No \
    --rainbow_prompt_separators=Round \
    --powerline_prompt_heads=Sharp \
    --powerline_prompt_tails=Flat \
    --powerline_prompt_style='Two lines, character and frame' \
    --prompt_connection=Solid \
    --powerline_right_prompt_frame=Yes \
    --prompt_connection_andor_frame_color=Darkest \
    --prompt_spacing=Sparse \
    --icons='Many icons' \
    --transient=No